export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const UPDATE_CUSTOMER = "REMOVE_CUSTOMER";
export const FETCH_ALL_DATABASE_TRANSACTIONS =
  "FETCH_ALL_DATABASE_TRANSACTIONS";
export const FETCH_TRANSACTIONS = " FETCH_TRANSACTIONS";
